# Generated by Django 2.1.7 on 2019-03-09 21:59

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('name', models.CharField(blank=True, default='', max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('set', 'Set'), ('part', 'Part'), ('minifig', 'Minifig'), ('gear', 'Gear')], default='part', max_length=16)),
                ('name', models.CharField(max_length=256)),
                ('number', models.CharField(max_length=32)),
                ('no_inventory', models.BooleanField(default=False)),
                ('year_released', models.PositiveIntegerField(default=0)),
                ('bl_id', models.PositiveIntegerField(default=0)),
                ('tlg_name', models.CharField(blank=True, default='', max_length=256)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bl_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=256)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='brixdb.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('number', models.PositiveIntegerField()),
                ('slug', models.SlugField(default='', editable=False, max_length=64)),
                ('tlg_name', models.CharField(blank=True, default='', max_length=256)),
                ('tlg_number', models.PositiveIntegerField(blank=True, null=True)),
                ('ldraw_name', models.CharField(blank=True, default='', max_length=256)),
                ('ldraw_number', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lego_ids', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('colour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='brixdb.Colour')),
            ],
        ),
        migrations.CreateModel(
            name='ItemInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_extra', models.BooleanField(default=False)),
                ('is_counterpart', models.BooleanField(default=False)),
                ('is_alternate', models.BooleanField(default=False)),
                ('match_id', models.PositiveIntegerField(blank=True, default=0)),
                ('element', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part_of', to='brixdb.Element')),
            ],
        ),
        migrations.CreateModel(
            name='ItemOwned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('catalogitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='brixdb.CatalogItem')),
            ],
            options={
                'ordering': ('number',),
            },
            bases=('brixdb.catalogitem',),
        ),
        migrations.AddField(
            model_name='itemowned',
            name='owned_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='brixdb.CatalogItem'),
        ),
        migrations.AddField(
            model_name='itemowned',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='iteminventory',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part_of', to='brixdb.CatalogItem'),
        ),
        migrations.AddField(
            model_name='iteminventory',
            name='part_of',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='brixdb.CatalogItem'),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='brixdb.Category'),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_brixdb.catalogitem_set+', to='contenttypes.ContentType'),
        ),
        migrations.CreateModel(
            name='Minifig',
            fields=[
            ],
            options={
                'ordering': ('name',),
                'proxy': True,
                'indexes': [],
            },
            bases=('brixdb.catalogitem',),
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
            ],
            options={
                'ordering': ('name',),
                'proxy': True,
                'indexes': [],
            },
            bases=('brixdb.catalogitem',),
        ),
        migrations.AddField(
            model_name='element',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='brixdb.Part'),
        ),
    ]
