# Generated by Django 2.1.7 on 2019-03-13 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brixdb', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='BricklinkCategory',
        ),
        migrations.DeleteModel(
            name='Minifig',
        ),
        migrations.DeleteModel(
            name='Part',
        ),
        migrations.AlterModelManagers(
            name='catalogitem',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='dimensions',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='year_released',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Minifig',
            fields=[
                ('catalogitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='brixdb.CatalogItem')),
            ],
            options={
                'ordering': ('name',),
            },
            bases=('brixdb.catalogitem',),
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('catalogitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='brixdb.CatalogItem')),
            ],
            options={
                'ordering': ('name',),
            },
            bases=('brixdb.catalogitem',),
        ),
        migrations.AlterField(
            model_name='ItemInventory',
            name='part_of',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='brixdb.CatalogItem'),
        ),
        migrations.AlterField(
            model_name='ItemInventory',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part_of', to='brixdb.CatalogItem'),
        ),
        migrations.AlterField(
            model_name='ItemOwned',
            name='owned_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='brixdb.CatalogItem'),
        ),
        migrations.AlterField(
            model_name='Element',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='brixdb.Part'),
        ),
        migrations.AlterField(
            model_name='ItemInventory',
            name='part_of',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='brixdb.CatalogItem'),
        ),
        migrations.AlterField(
            model_name='ItemInventory',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part_of', to='brixdb.CatalogItem'),
        ),
        migrations.AlterField(
            model_name='ItemOwned',
            name='owned_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='brixdb.CatalogItem'),
        ),
    ]
