# Generated by Django 2.1.7 on 2019-03-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brixdb', '0003_auto_20190313_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogitem',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True),
        ),
    ]
