# Generated by Django 2.1.7 on 2019-03-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brixdb', '0006_auto_20190324_1103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogitem',
            options={},
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='brickset_id',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='tlg_number',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='catalogitem',
            unique_together={('item_type', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='element',
            unique_together={('part', 'colour')},
        ),
    ]
