# Generated by Django 2.1.7 on 2019-05-08 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brixdb', '0008_auto_20190501_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='BricklinkOrder',
            fields=[
                ('catalogitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='brixdb.CatalogItem')),
                ('ordered', models.DateTimeField(blank=True, null=True)),
                ('seller_username', models.CharField(blank=True, default='', max_length=256)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('shipping', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('fees', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('currency', models.CharField(blank=True, default='', max_length=3)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bricklink_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('number',),
            },
            bases=('brixdb.catalogitem',),
        ),
        migrations.CreateModel(
            name='BulkLot',
            fields=[
                ('catalogitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='brixdb.CatalogItem')),
                ('acquired', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_lots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name', 'owner'),
            },
            bases=('brixdb.catalogitem',),
        ),
        migrations.CreateModel(
            name='LugbulkOrder',
            fields=[
                ('catalogitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='brixdb.CatalogItem')),
                ('period', models.CharField(max_length=8)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lugbulk_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('period', 'owner'),
            },
            bases=('brixdb.catalogitem',),
        ),
        migrations.RenameModel(
            old_name='ItemOwned',
            new_name='OwnedItem',
        ),
    ]
