# Generated by Django 2.2.3 on 2020-07-20 14:03

import django.contrib.auth.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brixdb', '0009_auto_20190508_2056'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='other_names',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='other_numbers',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='bl_id',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='item_type',
            field=models.CharField(choices=[('set', 'Set'), ('part', 'Part'), ('minifig', 'Minifig'), ('gear', 'Gear'), ('book', 'Book'), ('bricklink_order', 'Bricklink order'), ('lugbulk_order', 'Lugbulk order'), ('bulklot', 'Bulk lot')], default='part', max_length=16),
        ),
    ]
