# Generated by Django 3.0.8 on 2020-07-20 15:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brixdb', '0010_auto_20200720_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='colour',
            name='other_names',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
